name: scrape_anime

on:
  schedule:
    - cron: '0 1 * * *' 
  workflow_dispatch: 
    
jobs:
  anime-scrape:
    runs-on: macOS-latest
    env:
      ATLAS_URL: ${{ secrets.ATLAS_URL }}
      ATLAS_COLLECTION: ${{ secrets.ATLAS_COLLECTION }}
      ATLAS_DB: ${{ secrets.ATLAS_DB }}
    steps:
    - name: Start time
      run: echo "$(date) ** $(TZ=Asia/Jakarta date)"
      
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      
    - name: Install packages
      run: |
        Rscript -e 'install.packages(c("rvest", "tidyverse", "mongolite"), dependencies = TRUE)'
      shell: bash
      
    - name: Scrape Data Anime
      run: |
        Rscript -e '
        Web-Scraping-Anime-New.Rmd  
        '
      shell: bash
